# Use the official Jenkins image
FROM jenkins/jenkins:lts

# Switch to root user to install packages
USER root

# Install docker-compose
RUN apt-get update && \
    apt-get install -y curl && \
    curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

# Switch back to jenkins user
USER jenkins
